services:
  bookmarks:
    image: linkwise:latest
    container_name: linkwise-app
    ports:
      - "7500:7500"
    volumes:
      - ./data:/app/data
    secrets:
      - linkwise_secret_key
    restart: always

secrets:
  linkwise_secret_key:
    file: ./secrets/linkwise_secret_key
